oetc_m/Models/Dto/ApplicationRecordDto.cs
using oetc_m.Data.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace oetc_m.Models.Dto
{
    public class ApplicationRecordDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string AccessControlAddress { get; set; }
        public string Purpose { get; set; }
        public DateTime ApplicationTime { get; set; }
        public DateTime AgreeTime { get; set; }
        public DateTime LeaveTime { get; set; }
        public string EnterPictureSrc { get; set; }
        public string LeavePictureSrc { get; set; }
        public ApplicationStatus Status { get; set; }
        public string RecordCode { get; set; }
    }
}

oetc_m/Models/Dto/ApplicationSearchDto.cs
using oetc_m.Data.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace oetc_m.Models.Dto
{
    public class ApplicationSearchDto
    {
        public string Name { get; set; }

        public string PhoneNumber { get; set; }

        public List<string> AccessControlAddressList { get; set; }

        public List<ApplicationStatus> StatusList { get; set; }

        public List<DateTime> ApplicationTimeRange { get; set; }

        public DateTime AgreeTime { get; set; }

        public DateTime LeaveTime { get; set; }

        public int PageSize { get; set; }

        public int CurrentPage { get; set; }
    }
}

oetc_m/Models/ErrorViewModel.cs
using System;

namespace oetc_m.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

oetc_m/Models/PageObj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace oetc_m.Models
{
    public class PageObj
    {
        /// <summary>
        /// 总计记录数
        /// </summary>
        public int TotalCount { get; set; }

        /// <summary>
        /// 总页数
        /// </summary>
        public int TotalPages { get; set; }

        /// <summary>
        /// 每页最大记录数
        /// </summary>
        public int PageSize { get; set; }

        /// <summary>
        /// 当前页记录数
        /// </summary>
        public int CurrentCount { get; set; }

        /// <summary>
        /// 当前页数
        /// </summary>
        public int CurrentPage { get; set; }

    }
}

oetc_m/Models/ResponsePageObj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace oetc_m.Models
{
    public class ResponsePageObj<T>
    {
        /// <summary>
        /// 是否成功 0：成功，1：默认失败，其他值 都是失败
        /// 1：操作失败
        /// 2：系统异常
        /// 3：未登录
        /// 4：请求参数错误
        /// 5：对象不存在
        /// </summary>
        public int Code { get; set; }

        public string Msg { get; set; }

        public bool Success { get; set; }

        public PageObj Page { get; set; }

        public List<T> Data { get; set; }

        public ResponsePageObj()
        {
            Data = new List<T>();
            Page = new PageObj();
            Code = 1;
            Msg = "Fail";
            Success = false;
        }
    }
}

oetc_m/Models/ReturnObj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace oetc_m.Models
{
     public class ReturnObj<T>
     {
         public int Code { get; set; }
         public T Data { get; set; }
         public string Msg { get; set; }
         public bool Success{ get; set; }
        public ReturnObj()
        {
            Code = 1;
            Msg = "Fail";
            Success = false;
        }
     }
}

oetc_m/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace oetc_m.Controllers
{
    public class ApplicationController : Controller
    {
        public IActionResult ApplicationRecord()
        {
            return View();
        }
        public IActionResult ApplicationDetail(int id)
        {
            ViewData["id"] = id;
            return View();
        }
    }
}

oetc_m/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using oetc_m.Models;

namespace oetc_m.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

oetc_m/Views/Application/ApplicationDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link href="~/element-ui@2.11.0/theme-chalk/index.css" rel="stylesheet" />
<link href="~/element-ui@2.11.0/theme-chalk/index-black.css" rel="stylesheet" />
<link href="~/element-ui@2.11.0/theme-chalk/icon.css" rel="stylesheet" />
<body>
    <div id="text-center">
        <template>
            <el-row>
                <el-col :span="24" style="text-align:center;font-size:18px;padding-bottom:20px">
                    申请详情
                    <el-tag type="warning" v-if="form.status==1">已申请</el-tag>
                    <el-tag type="success" v-if="form.status==3">已退出</el-tag>
                </el-col>
            </el-row>
            <el-row>
                <el-form ref="form" :model="form" label-width="95px" disabled>
                    <el-row>
                        <el-col :span="12">
                            <el-form-item label="使用人" >
                                <el-input v-model="form.name"></el-input>
                            </el-form-item>
                        </el-col>
                        <el-col :span="12">
                            <el-form-item label="号码">
                                <el-input v-model="form.phoneNumber"></el-input>
                            </el-form-item>
                        </el-col>
                    </el-row>
                    <el-row>
                        <el-col :span="12">
                            <el-form-item label="门禁地址">
                                <el-input v-model="form.accessControlAddress"></el-input>
                            </el-form-item>
                        </el-col>
                    </el-row>
                    <el-form-item label="进入目的">
                        <el-input v-model="form.purpose"></el-input>
                    </el-form-item>
                    <el-row>
                        <el-col :span="12">
                            <el-form-item label="申请时间">
                                <el-date-picker type="date" placeholder="" v-model="form.applicationTime" style="width: 100%;"></el-date-picker>
                            </el-form-item>
                        </el-col>
                        <el-col :span="12">
                            <el-form-item label="退出时间">
                                <el-date-picker type="date" placeholder="" v-model="form.leaveTime" style="width: 100%;"></el-date-picker>
                            </el-form-item>
                        </el-col>
                    </el-row>
                    <el-row>
                        <el-col :span="12">
                            <el-form-item label="进入前照片">
                                <el-image :src="form.enterPictureSrc">
                                    <div slot="error" class="image-slot">
                                        <i class="el-icon-picture-outline"></i>
                                    </div>
                                </el-image>
                            </el-form-item>
                        </el-col>
                        <el-col :span="12">
                            <el-form-item label="离开前照片">
                                <el-image :src="form.leavePictureSrc">
                                    <div slot="error" class="image-slot">
                                        <i class="el-icon-picture-outline">还未离开</i>
                                    </div>
                                </el-image>
                            </el-form-item>
                        </el-col>
                    </el-row>
                        
                </el-form>
            </el-row>
        </template>
    </div>
    <script src="~/js/vue.min.js"></script>
    <script src="~/element-ui@2.11.0/index.js"></script>
    <script>
        var Main = {
            data() {
                return {
                    form: {
                        name: '',
                        accessControlAddress: '',
                        purpose: '',
                        applicationTime: '',
                        leaveTime: '',
                        enterPictureSrc: '',
                        leavePictureSrc: '',
                        phoneNumber: '',
                        status:void 0
                    }
                }
            },
            methods: {
                getDetail() {
                    let _self = this;
                    $.ajax({
                        type: 'GET',
                        dataType: 'json',
                        url: '../../api/application/application/@ViewData["id"]',
                        success: function (res) {
                            if (res.success) {
                                _self.form = res.data;
                                console.log(_self.form);
                            }
                        },
                    });
                }
            },
            created() {
                this.getDetail();
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#text-center');
    </script>
</body>

oetc_m/Views/Application/ApplicationRecord.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<link href="~/element-ui@2.11.0/theme-chalk/index.css" rel="stylesheet" />
<link href="~/element-ui@2.11.0/theme-chalk/index-black.css" rel="stylesheet" />
<link href="~/element-ui@2.11.0/theme-chalk/icon.css" rel="stylesheet" />
<body>
    <div id="text-center">
        <template>
            <el-row>
                <el-form :inline="true" size="small">
                    <el-form-item label="申请状态" >
                        <el-select v-model="status" placeholder="请选择申请状态" multiple>
                            <el-option v-for="item in options"
                                       :key="item.value"
                                       :label="item.label"
                                       :value="item.value">
                            </el-option>
                        </el-select>
                    </el-form-item>
                    <el-form-item label="使用人">
                        <el-input v-model="user" placeholder="使用人姓名"></el-input>
                    </el-form-item>
                    <el-form-item label="号码">
                        <el-input v-model="phoneNumber" placeholder="号码"></el-input>
                    </el-form-item>
                    <el-form-item label="门禁地址">
                        <el-select v-model="address" placeholder="请选择门禁地址" multiple>
                            <el-option v-for="item in addressList"
                                       :key="item.accessControlAddressName"
                                       :label="item.accessControlAddressName"
                                       :value="item.accessControlAddressName">
                            </el-option>
                        </el-select>
                    </el-form-item>
                    <el-form-item label="申请时间">
                        <el-date-picker v-model="applicationTime"
                                        type="datetimerange"
                                        :picker-options="pickerOptions"
                                        range-separator="至"
                                        start-placeholder="开始日期"
                                        end-placeholder="结束日期"
                                        align="right">
                        </el-date-picker>
                    </el-form-item>
                    <el-form-item>
                        <el-button type="primary" v-on:click="queryBtn">查询</el-button>
                    </el-form-item>
                </el-form>
            </el-row>
            <el-row>
                <el-table :data="tableData"
                          style="width: 100%" v-loading="loading">
                    <el-table-column align="right">
                        <template slot="header" slot-scope="scope">
                            <el-button type="primary" v-on:click="creatExcel()" size="small">导出到excel</el-button>
                        </template>
                        <el-table-column prop="id" label="id" width="50"></el-table-column>
                        <el-table-column prop="name" label="使用人" width="100"></el-table-column>
                        <el-table-column prop="accessControlAddress" label="门禁地址" width="150"></el-table-column>
                        <el-table-column prop="applicationTime" label="申请时间" width="160"></el-table-column>
                        @*<el-table-column prop="agreeTime" label="同意时间" width="160">
                            <template slot-scope="scope">
                                <el-tag type="danger" v-if="scope.row.status == 1">申请中</el-tag>
                                <div v-else>{{scope.row.agreeTime}}</div>
                            </template>
                        </el-table-column>*@
                        <el-table-column prop="leaveTime" label="离开时间" width="160">
                            @*<template slot-scope="scope">
                                <el-tag type="danger" v-if="scope.row.status == 1">申请中</el-tag>
                                <el-tag type="danger" v-if="scope.row.status == 2">未退出</el-tag>
                                <div v-else>{{scope.row.leaveTime}}</div>
                            </template>*@
                        </el-table-column>
                        <el-table-column prop="status" label="状态" width="120">
                            <template slot-scope="scope">
                                <el-tag type="success" v-if="scope.row.status == 3">已退出</el-tag>
                                <el-tag v-if="scope.row.status == 2">已同意进入</el-tag>
                                <el-tag type="danger" v-if="scope.row.status == 1">已申请</el-tag>
                            </template>
                        </el-table-column>
                        <el-table-column prop="recordCode" label="编码" width="100"></el-table-column>
                        <el-table-column label="操作">
                            <template slot-scope="scope">
                                <el-button size="mini"
                                           v-on:click="detail(scope.row.id)">查看详情</el-button>
                            </template>
                        </el-table-column>
                </el-table>
            </el-row>
            <el-row>
                <el-pagination v-on:size-change="handleSizeChange"
                               v-on:current-change="handleCurrentChange"
                               :current-page="page.currentPage"
                               :page-sizes="[10, 20, 30, 40]"
                               :page-size=page.pageSize
                               layout="total, sizes, prev, pager, next, jumper"
                               :total=page.total>
                </el-pagination>
            </el-row>
        </template>
    </div>

    <script src="~/js/vue.min.js"></script>
    <script src="~/element-ui@2.11.0/index.js"></script>
    <script>
        var Main = {
            data() {
                return {
                    pickerOptions: {
                        shortcuts: [{
                            text: '最近一周',
                            onClick(picker) {
                                const end = new Date();
                                const start = new Date();
                                start.setTime(start.getTime() - 3600 * 1000 * 24 * 7);
                                picker.$emit('pick', [start, end]);
                            }
                        }, {
                            text: '最近一个月',
                            onClick(picker) {
                                const end = new Date();
                                const start = new Date();
                                start.setTime(start.getTime() - 3600 * 1000 * 24 * 30);
                                picker.$emit('pick', [start, end]);
                            }
                        }, {
                            text: '最近三个月',
                            onClick(picker) {
                                const end = new Date();
                                const start = new Date();
                                start.setTime(start.getTime() - 3600 * 1000 * 24 * 90);
                                picker.$emit('pick', [start, end]);
                            }
                        }]
                    },
                    applicationTime:[],
                    user: '',
                    phoneNumber:'',
                    status: [],
                    options: [
                        {
                            value: 1,
                            label: "已申请"
                        },
                        {
                            value: 2,
                            label: "已同意进入"
                        },
                        {
                            value: 3,
                            label: "已退出"
                        }
                    ],
                    address: [],
                    addressList:[],
                    tableData: [],
                    loading:false,
                    page: {
                        currentPage: 1,
                        total: 0,
                        pageSize:10,
                    }
                }
            },
            methods: {
                creatExcel() {
                    data = {
                        "user": this.user,
                        "phoneNumber": this.phoneNumber,
                        "statusList": this.status,
                        "accessControlAddressList": this.address,
                        "applicationTimeRange": this.applicationTime,
                        "currentPage": this.page.currentPage,
                        "pageSize": this.page.pageSize
                    };
                    let _self = this;
                    $.ajax({
                        type: 'post',
                        dataType: 'json',
                        url: '../../api/application/excel/create',
                        contentType: 'application/json',
                        data: JSON.stringify(data),
                        success: function (data) {
                            if (data.success) {
                            }
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            if (errorThrown == "Unauthorized") {
                                window.parent.MainIndex.openLoginFrom();
                                _self.$message({
                                    type: 'error',
                                    message: XMLHttpRequest.responseJSON.msg
                                });
                            } else {
                                _self.$message({
                                    type: 'error',
                                    message: errorThrown
                                });
                            }
                        }
                    });
                },
                submitQuery() {
                    data = {
                        "user": this.user,
                        "phoneNumber": this.phoneNumber,
                        "statusList": this.status,
                        "accessControlAddressList": this.address,
                        "applicationTimeRange": this.applicationTime,
                        "currentPage": this.page.currentPage,
                        "pageSize": this.page.pageSize
                    };
                    let _self = this;
                    this.loading = true;
                    $.ajax({
                        type: 'post',
                        dataType: 'json',
                        url: '../../api/application/application/query',
                        contentType:'application/json',
                        data: JSON.stringify(data),
                        success: function (data) {
                            if (data.success) {
                                _self.tableData = data.data;
                                _self.page.total = data.page.totalCount;
                                _self.loading = false;
                            }
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            if (errorThrown == "Unauthorized") {
                                window.parent.MainIndex.openLoginFrom();
                                _self.$message({
                                    type: 'error',
                                    message: XMLHttpRequest.responseJSON.msg
                                });
                            } else {
                                _self.$message({
                                    type: 'error',
                                    message: errorThrown
                                });
                            }
                        }
                    });
                },
                queryBtn() {
                    this.submitQuery();
                },
                getAddressList() {
                    let _self = this;
                    $.ajax({
                        type: 'get',
                        url: '../../api/address',
                        success: function (data) {
                            _self.addressList = data;
                        }
                    });
                },
                handleSizeChange(val) {
                    this.page.pageSize = val;
                    this.submitQuery();
                },
                handleCurrentChange(val) {
                    this.page.currentPage = val;
                    this.submitQuery();
                },
                detail(id) {
                    window.open("/application/applicationdetail?id="+id);  
                }
            },
            created() {
                this.getAddressList();
                this.submitQuery();
            }
        };
        var Ctor = Vue.extend(Main);
        new Ctor().$mount('#text-center');
    </script>
</body>

oetc_m/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

oetc_m/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - oetc_m</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/element-ui@2.11.0/theme-chalk/index.css" rel="stylesheet" />
    <link href="~/element-ui@2.11.0/theme-chalk/index-black.css" rel="stylesheet" />
    <link href="~/element-ui@2.11.0/theme-chalk/icon.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/vue.min.js"></script>
    <script src="~/element-ui@2.11.0/index.js"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">oetc_m</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Application" asp-action="ApplicationRecord">申请记录</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="Privacy">地址管理</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
            &copy; 2020 - oetc_m - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    
</body>
</html>